// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALX2J5cCAfuDAsSRLMmWKl4Dl58PZo6VI',
    appId: '1:423681381424:web:dea5a86e5e86f0788509f5',
    messagingSenderId: '423681381424',
    projectId: 'project2-22b48',
    authDomain: 'project2-22b48.firebaseapp.com',
    storageBucket: 'project2-22b48.firebasestorage.app',
    measurementId: 'G-SDB8P40340',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWFIxeO0j5Pf-1tfMtPnZWDMi-U9IALqQ',
    appId: '1:423681381424:android:afb5b61a8b12887d8509f5',
    messagingSenderId: '423681381424',
    projectId: 'project2-22b48',
    storageBucket: 'project2-22b48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDla9OsR835mtXYH2j2BNYuKbspSIoQbU',
    appId: '1:423681381424:ios:f19fa16e3661d9de8509f5',
    messagingSenderId: '423681381424',
    projectId: 'project2-22b48',
    storageBucket: 'project2-22b48.firebasestorage.app',
    iosBundleId: 'com.example.midicalLaboratory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDla9OsR835mtXYH2j2BNYuKbspSIoQbU',
    appId: '1:423681381424:ios:f19fa16e3661d9de8509f5',
    messagingSenderId: '423681381424',
    projectId: 'project2-22b48',
    storageBucket: 'project2-22b48.firebasestorage.app',
    iosBundleId: 'com.example.midicalLaboratory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALX2J5cCAfuDAsSRLMmWKl4Dl58PZo6VI',
    appId: '1:423681381424:web:a7720d3c60c01d378509f5',
    messagingSenderId: '423681381424',
    projectId: 'project2-22b48',
    authDomain: 'project2-22b48.firebaseapp.com',
    storageBucket: 'project2-22b48.firebasestorage.app',
    measurementId: 'G-EW8245PT2K',
  );
}
